### ISSUE TITLE
Package Deprecated?

### ISSUE THREAD

**Issue by DerekTBrown** [stoeffel/inquander#2]
This package is using an extremely out of date version of inquirer.  Will this be updated in the near future?

**Comment by stoeffel** [comment]
not by me. feel free to make a pull request, or create something new based on this.

**Comment by DerekTBrown** [comment]
I went ahead and updated per #3 .  If you are looking for a long-term maintainer, I would definitely be interested, this is at the core of one of my new apps.

**Comment by stoeffel** [comment]
I would be happy if you would take it over. will add you to github and npm. what's your npm username

**Comment by DerekTBrown** [comment]
It's derektbrown as well

**Comment by stoeffel** [comment]
done! thanks for taking this over ❤️
